---

- hosts: all
  become: true
  tasks:

  - name: install apache2 package, php packages for ubuntu and update repository index
    apt:
      name:
        - apache2
        - libapache2-mod-php
      state: latest
      update_cache: yes
    when: ansible_distribution == "Ubuntu"

# for CentOS

  - name: install httpd package, php support for apache and update repository index
    dnf:
      name: 
        - httpd
        - php
      state: latest
      update_cache: yes
    when: ansible_distribution == "CentOS"

