---

- hosts: all
  become: true
  tasks:

  - name: install apache2 package, php packages for ubuntu and update repository index
    package:
      name:
        - "{{ apache_package }}"
        - "{{ php_package }}"
      state: latest
      update_cache: yes

