#========= this are the tasks that will be running on all servers========================================
- hosts: all
  become: true
  pre_tasks:
# pre_tasks: #   Tasks listed under `pre_tasks` run BEFORE the main `tasks` section.
#   Common uses:
#     - Preparing the environment
#     - Installing prerequisites
#     - Validating conditions before the main play runs
#     - Setting facts or variables early
#   These tasks execute after host selection and fact gathering.


  - name: install updates (CentOS)
    tags: always
    dnf:
      update_only: yes
      update_cache: yes
    when: ansible_distribution == "CentOS"

  - name: install updates (Ubuntu)
    tags: always
    apt:
      upgrade: dist
      update_cache: yes
    when: ansible_distribution == "Ubuntu"

- hosts: workstations
  become: true
  tasks:

  - name: install unzip
    package:
      name: unzip

  - name: install terraform
    unarchive:
      src: https://releases.hashicorp.com/terraform/0.12.28/terraform_0.12.28_linux_amd64.zip
      dest: /usr/local/bin
      remote_src: yes
      mode: 0755
      owner: root
      group: root

#========== this are the tasks that will be running on web_servers only ====================================
- hosts: web_servers
  become: true
  tasks:

  - name: install apache and php for ubuntu servers
    tags: apache,centos,httpd
    apt:
      name:
        - apache2
        - libapache2-mod-php
      state: latest
      update_cache: yes
    when: ansible_distribution == "Ubuntu"

  - name: install apache and php for CentOS
    tags: apache,centos,httpd
    dnf:
      name:
        - httpd
        - php
      state: latest
      update_cache: yes
    when: ansible_distribution == "CentOS"

  - name: start httpd (CentOS)
    tags: apache,centos,httpd
    service:
      name: httpd
      state: started
      enabled: yes
    when: ansible_distribution == "CentOS"

  - name: copy default html file for site
    tags: apache,apache2,httpd
    copy:
      src: default_site.html
      dest: /var/www/html/index.html
      owner: root
      group: root
      mode: 0644
#========== this are the tasks that will be running on db_servers only ====================================

- hosts: db_servers
  become: true
  tasks:

  - name: install mariadb package (Ubuntu)
    tags: ubuntu,db,mariadb
    apt:
      name: mariadb-server
      state: latest
    when: ansible_distribution == "Ubuntu"

  - name: install mariadb package (CentOS)
    tags: centos,db,mariadb
    dnf:
      name: mariadb
      state: latest
    when: ansible_distribution == "CentOs"

#========== this are the tasks that will be running on file_servers only ====================================\

- hosts: file_servers
  become: true
  tasks:

  - name: install samba package (Ubuntu)
    tags: samba
    package:
      name: samba
      state: latest
    when: ansible_distribution == "Ubuntu"

  - name: install samba package (CentOS)
    tags: samba
    package:
      name: samba
      state: latest
    when: ansible_distribution == "CentOS"
